name: CI/CD Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Backend Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mean-app-backend:latest ./backend

    - name: Build Frontend Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mean-app-frontend:latest ./frontend

    - name: Push Backend Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/mean-app-backend:latest

    - name: Push Frontend Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/mean-app-frontend:latest

    - name: SSH and Deploy on VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_IP }}
        username: ubuntu
        key: ${{ secrets.VM_KEY }}
        script: |
          cd ~/mean-app
          docker-compose pull
          docker-compose down
          docker-compose up -d --build
