name: CI/CD Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch: 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker Images
      run: docker-compose build

    - name: Push Docker Images
      run: docker-compose push

    - name: SSH and Deploy on VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_IP }}
        username: ubuntu
        key: ${{ secrets.VM_KEY }}
        script: |
          cd ~/mean-app
          docker-compose pull
          docker-compose down
          docker-compose up -d --build
